from GatorHelper import GatorLibrary

if __name__ == "__main__":
    
    lib = GatorLibrary()

    lib.InsertBook(101, "Introduction to Algorithms", "Thomas H. Cormen", "Yes")
    lib.InsertBook(48, "Data Structures and Algorithms", "Sartaj Sahni", "Yes")
    #lib.PrintBook(48)
    lib.InsertBook(132, "Operating System Concepts", "Abraham Silberschatz", "Yes")
    lib.InsertBook(25, "Computer Networks", "Andrew S. Tanenbaum", "Yes")
    lib.BorrowBook(120, 48, 2)
    lib.BorrowBook(132, 101, 1)
    lib.InsertBook(73, "Introduction to the Theory of Computation", "Michael Sipser", "Yes")
    lib.InsertBook(12, "Artificial Intelligence: A Modern Approach", "Stuart Russell", "Yes")
    lib.InsertBook(6, "Database Management Systems", "Raghu Ramakrishnan", "Yes")
    lib.BorrowBook(144, 48, 3)
    lib.BorrowBook(140, 48, 3)
    lib.BorrowBook(142, 48, 2)
    lib.BorrowBook(138, 12, 4)
    lib.BorrowBook(150, 12, 3)
    lib.BorrowBook(162, 12, 1)
    lib.ReturnBook(120, 48)
    #lib.FindClosestBook(9)
    lib.DeleteBook(12)
    #lib.ColorFlipCount()
    lib.InsertBook(125, "Computer Organization and Design", "David A. Patterson", "Yes")
    lib.InsertBook(180, "Introduction to Software Engineering", "Ian Sommerville", "Yes")
    lib.BorrowBook(111, 73, 3)
    lib.BorrowBook(52, 73, 1)
    lib.InsertBook(115, "Operating Systems: Internals and Design Principles", "William Stallings", "Yes")
    lib.BorrowBook(153, 25, 2)
    #lib.PrintBooks(10, 150)
    lib.InsertBook(210, "Machine Learning: A Probabilistic Perspective", "Kevin P. Murphy", "Yes")
    lib.BorrowBook(171, 25, 3)
    lib.BorrowBook(2, 132, 2)
    #lib.FindClosestBook(50)
    lib.BorrowBook(18, 101, 2)
    lib.InsertBook(80, "Software Engineering: A Practitioner's Approach", "Roger S. Pressman", "Yes")
    lib.BorrowBook(210, 210, 1)
    lib.BorrowBook(43, 73, 1)
    lib.InsertBook(60, "Introduction to Computer Graphics", "David F. Rogers", "Yes")
    #lib.PrintBook(210)
    lib.InsertBook(4, "Design Patterns: Elements of Reusable Object-Oriented Software", "Erich Gamma", "Yes")
    lib.InsertBook(2, "Introduction to the Theory of Computation", "Michael Sipser", "Yes")
    lib.BorrowBook(34, 210, 2)
    lib.InsertBook(65, "Computer Networks: Principles, Protocols, and Practice", "Olivier Bonaventure", "Yes")
    #lib.ColorFlipCount()
    lib.DeleteBook(125)
    lib.DeleteBook(115)
    lib.DeleteBook(210)
    #lib.ColorFlipCount()
    lib.DeleteBook(25)
    lib.DeleteBook(80)
    #lib.ColorFlipCount()
    #lib.Quit()
